baseurl: '/laconga-edu.github.io/'
exclude: ['README.md']
permalink: pretty
title: 'LA-CoNGA Edu'

google_analytics_id: null
homepage:
  show_call_box: true
logo:
  mobile: "images/logo/logo-la.png"
  desktop: "images/logo/logo-la.png"
  desktop_height: "36px"
footer:
  copyright_text: 'LA-CoNGA Organization. Theme by <a class="zerostatic" href="https://www.zerostatic.io">www.zerostatic.io</a>. Work under MIT License'

seo:
  meta_og_title: "LA-CoNGA Edu"
  meta_og_type: "website"
  meta_og_url: "http://laconga.redclara.net/"
  meta_og_image: "https://raw.githubusercontent.com/zerostaticthemes/jekyll-serif-theme/master/screenshots/tn.png"
  meta_og_description: "LA-CoNGAphysics es una alianza integrada por 11 universidades en América Latina y Europa, con el fin de construir una plataforma virtual de aprendizaje en Física Avanzada en Colombia, Ecuador, Perú y Venezuela."
  meta_twitter_card: "summary"
  meta_twitter_site: "@lacongaphysics"
  meta_twitter_creator: "@lacongaphysics"

collections:
  services:
    output: true
    permalink: /services/:path/
  team:
    output: true
    permalink: /team/:path/

defaults:
  - scope:
      type: services
    values:
      layout: service
      bodyClass: page-services-single
  - scope:
      path: 'images'
    values:
      image: true

sass:
  style: compact # possible values: nested expanded compact compressed

plugins:
  - jekyll-environment-variables
